<?php


namespace App\Form;


use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\Form\FormView;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ImageFileWithPreviewType extends AbstractType
{
  public function configureOptions(OptionsResolver $resolver)
  {
    $resolver->setDefaults(array(
      'required' => false,
      'data_class' => null,
      'attr' => array(
        'accept' => 'image/jpeg,image/png',
      ),

      'data_attribute' => null
    ));
  }

  public function getParent()
  {
    return FileType::class;
  }

  public function buildView(FormView $view, FormInterface $form, array $options)
  {
    if(isset($options['data_attribute'])){
      $view->vars['data_attribute'] = $options['data_attribute'];
    }

//    parent::buildView($view, $form, $options); // TODO: Change the autogenerated stub
  }


  public function getBlockPrefix()
  {
    return 'image_file_with_preview';
  }
}
